### ISSUE TITLE
Client pg vs postgres

### ISSUE THREAD

**Issue by jonaskello** [Vincit/knex-db-manager#23]
The examples in the [knex docs](http://knexjs.org/) uses `client: 'pg'` but `knex-db-manager` requires `client: 'postgres'`. I'm curious about the reason for this? Could both be supported?

**Comment by elhigu** [comment]
I think that `{ client: 'pg' }` works also just fine. Did it throw an error? In knex 'pg' and 'postgres' are aliases for the same client.

**Comment by jonaskello** [comment]
Yes, I get this error when I use `pg`:

```
$ ts-node scripts/create-db.ts

C:\code\XXX\node_modules\knex-db-manager\lib\index.js:29
        throw new Error(config.knex.client + ' is not supported. Supported clients currently: postgres, mysql and sqlite');
              ^
Error: pg is not supported. Supported clients currently: postgres, mysql and sqlite
    at Object.databaseManagerFactory (C:\code\XXX\node_modules\knex-db-manager\lib\index.js:29:15)
    at Object.<anonymous> (C:\code\XXX\scripts\create-db.ts:14:19)
    at Module._compile (module.js:569:30)
    at Module.m._compile (C:\code\XXX\node_modules\ts-node\src\index.ts:379:23)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\code\XXX\node_modules\ts-node\src\index.ts:382:1
2)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at Object.<anonymous> (C:\code\XXX\node_modules\ts-node\src\_bin.ts:180:12)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
error Command failed with exit code 1.
```

**Comment by elhigu** [comment]
Ah right, I need to add aliases / check them from knex for selecting used implementation. Thanks for  the report.

**Comment by mitchellporter** [comment]
Hey @elhigu I realize this is a simple fix but I've been enjoying this and `objection.js` so i'd like to help in any way possible :)

Before I submit a PR for this though, I submitted a PR that adds a `.gitignore` file here: https://github.com/Vincit/knex-db-manager/pull/26

**Comment by elhigu** [comment]
Looks like merging that other PR closed this one automatically :) Reopened.

**Comment by mitchellporter** [comment]
Ha! I was wondering why you had closed it :)

I'll submit the PR soon thanks.

**Comment by elhigu** [comment]
List of aliases are found here https://github.com/tgriesser/knex/blob/master/src/index.js#L12 fixing it in a moment.
