### ISSUE TITLE
Does not exit on failed authentication

### ISSUE THREAD

**Issue by jonaskello** [Vincit/knex-db-manager#24]
If I use an invalid password `knex-db-manager` gives this error, which I think can be OK. But it does not exit back to the prompt which I think is a problem.

```
Unhandled rejection error: password authentication failed for user "userwithrightstocreateusersanddatabases"
    at Connection.parseE (C:\code\XXX\node_modules\pg\lib\connection.js:567:11)
    at Connection.parseMessage (C:\code\XXXnode_modules\pg\lib\connection.js:391:17)
    at Socket.<anonymous> (C:\code\XXX\node_modules\pg\lib\connection.js:129:22)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at Socket.Readable.push (_stream_readable.js:197:10)
    at TCP.onread (net.js:588:20)
```

**Comment by jonaskello** [comment]
Same problem with trying to create an existing database. My expectation would be that the program should crash with non-zero exit code in these cases but it does not exit. I guess more error handling is needed for some promises.

```
$ ts-node scripts/create-db.ts
Unhandled rejection error: database "XXX" already exists
    at Connection.parseE (C:\code\XXX\diaq-app\node_modules\pg\lib\connection.js:567:11)
    at Connection.parseMessage (C:\code\XXX\diaq-app\node_modules\pg\lib\connection.js:391:17)
    at Socket.<anonymous> (C:\code\XXX\diaq-app\node_modules\pg\lib\connection.js:129:22)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at Socket.Readable.push (_stream_readable.js:197:10)
    at TCP.onread (net.js:588:20)
```

**Comment by elhigu** [comment]
There are db connections left open, even when some queries fail. You need to add error handling and call https://vincit.github.io/knex-db-manager/#close and maybe https://vincit.github.io/knex-db-manager/#closeKnex to close connections (the same way that you need to call knex.destroy() when exitting app that has been using knex and has open connections in pool).

Connections cannot be closed automatically on error, because you actually might like to keep doing queries even when there has been an error.

**Comment by jonaskello** [comment]
Yes, you are correct. So I tried this, and it prints the closing messages but does not exit. Maybe I am doing something else wrong...

```
dbManager.createDb()
  .catch((e) => {
    console.log(`Error occured when creating database: ${e}`);
    dbManager.close().then(() => console.log("closed connection 1"));
    dbManager.closeKnex().then(() => console.log("closed connection 2"));
  });
```

```
Error occured when creating database: error: database "XXX" already exists
closed connection 2
closed connection 1
```

**Comment by jonaskello** [comment]
It seems this is more of a knex issue. I can reproduce using a simple Knex instance, doing a .raw call and then calling knex.destory(). It still does not exit.

**Comment by elhigu** [comment]
I'll check out if I can reproduce this with knex and report the error.
