### ISSUE TITLE
Multiple database creations fail in postgres

### ISSUE THREAD

**Issue by theogravity** [Vincit/knex-db-manager#29]
Reference issue (not mine) - https://github.com/elixir-ecto/ecto/issues/1925

I'm using the db manager to create multiple databases at once - doing so however gets me this error

```
{ error: source database "template1" is being accessed by other users
        at Connection.Object.<anonymous>.Connection.parseE (/root/app/node_modules/pg/lib/connection.js:567:11)
        at Connection.Object.<anonymous>.Connection.parseMessage (/root/app/node_modules/pg/lib/connection.js:391:17)
        at Socket.<anonymous> (/root/app/node_modules/pg/lib/connection.js:129:22)
        at emitOne (events.js:115:13)
        at Socket.emit (events.js:210:7)
        at addChunk (_stream_readable.js:252:12)
        at readableAddChunk (_stream_readable.js:239:11)
        at Socket.Readable.push (_stream_readable.js:197:10)
        at TCP.onread (net.js:589:20)
```

According to the referenced issue, db creation should be done logged into the `postgres` database - I'm guessing that by default it's logging in using the `template1` for superuser.

**Comment by elhigu** [comment]
Interesting. I had no idea that database cannot be created from other when there are other connections to the source database active. I will fix this. Thanks for the report!
